config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('ecommerce.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^catalogue/', include('ecommerce.apps.catalogue.urls', namespace="catalogue")),
    url(r'^cart/', include('ecommerce.apps.cart.urls', namespace="cart")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ecommerce/apps/cart/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView

    url(
        regex=r'^(?P<pk>\d+)$',
        view=views.CartDetailView.as_view(),
        name='cart_detail'
    ),

    url(
        regex=r'^add-to-cart/(?P<product_id>\d+)$',
        view=views.AddToCart.as_view(),
        name='add_to_cart'
    ),

    url(
        regex=r'^remove-from-cart/(?P<product_id>\d+)$',
        view=views.RemoveFromCart.as_view(),
        name='remove_from_cart'
    ),

    url(
        regex=r'^checkout/(?P<cart_id>\d+)$',
        view=views.CheckoutView.as_view(),
        name='checkout'
    ),

]

ecommerce/apps/catalogue/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^items/(?P<category_slug>[\w-]+)/$',
        view=views.ProductListView.as_view(),
        name='product_list_category'
    ),

    url(
        regex=r'^search/$',
        view=views.ProductSearchView.as_view(),
        name='search'
    ),

    url(
        regex=r'^(?P<product_slug>[\w-]+)/$',
        view=views.ProductDetailView.as_view(),
        name='product_detail'
    ),
]

ecommerce/apps/catalogue/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class Category(TimeStampedModel):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Product(TimeStampedModel):

    title = models.CharField(max_length=255)
    categories = models.ManyToManyField(Category)
    price = models.FloatField()
    special_price = models.FloatField(null=True)
    base_image = models.ImageField(null=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.title


class AdditionalImages(TimeStampedModel):
    image = models.FileField()
    product = models.ForeignKey(Product, related_name='additional_images')

ecommerce/apps/catalogue/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.db.models import Q

from .models import Product, Category


class ProductListView(ListView):
    model = Product
    template_name = "product_list.html"
    paginate_by = 21

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs.get("category_slug"))
        return Product.objects.filter(categories=category)


class ProductSearchView(ListView):
    model = Product
    template_name = "product_list.html"
    paginate_by = 21

    def get_queryset(self):
        query = self.request.GET.get('q').lower()
        products = Product.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query)
        )
        return products


class ProductDetailView(DetailView):
    model = Product
    slug_url_kwarg = 'product_slug'
    template_name = "product_detail.html"

ecommerce/apps/catalogue/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-7">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img style="max-height:400px" src="{{MEDIA_URL}}{{object.base_image}}" alt="First slide">
        </div>
        {% for each_image in object.additional_images.all %}
          <div class="carousel-item">
          <img style="max-height:400px" src="{{MEDIA_URL}}{{each_image.image}}" alt="First slide">
        </div>
        {% endfor %}
      </div>
      <a class="left carousel-control" style="background-image: none" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="icon-prev" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" style="background-image: none" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="icon-next" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

  </div>
  <div class="col-md-5">
    <h1>{{object.title}}</h1>
    <h3>${{object.price}}</h3>
    <p>{{product.description | safe}}</p>
    <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-large btn-primary">Add to Cart</a>
  </div>
</div>

{% endblock content %}

ecommerce/apps/catalogue/templates/product_list.html
{% extends 'base.html' %}

{% block content %}
 <div class="card-columns">

  {% for product in object_list %}
      <div class="card">
        <a href="{% url 'catalogue:product_detail' product.slug %}">
          <img class="img-fluid" style="max-height:200px" src="{{MEDIA_URL}}{{product.base_image}}" alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title">{{product.title}}</h4>
            <p class="card-text">${{product.price}}</p>
          </div>
        </a>
      </div>

  {% endfor %}

  </div>

  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% endif %}
        {% for each_page in page_obj.paginator.page_range %}
          <li class="page-item {% if each_page == page_obj.number %} active {% endif %}"><a class="page-link" href="?page={{each_page}}" >{{each_page}}</a></li>
        {% endfor %}
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    {% endif %}

{% endblock content %}