config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('ecommerce.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^catalogue/', include('ecommerce.apps.catalogue.urls', namespace="catalogue")),
    url(r'^cart/', include('ecommerce.apps.cart.urls', namespace="cart")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ecommerce/apps/cart/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView

    url(
        regex=r'^(?P<pk>\d+)$',
        view=views.CartDetailView.as_view(),
        name='cart_detail'
    ),

    url(
        regex=r'^add-to-cart/(?P<product_id>\d+)$',
        view=views.AddToCart.as_view(),
        name='add_to_cart'
    ),

    url(
        regex=r'^remove-from-cart/(?P<product_id>\d+)$',
        view=views.RemoveFromCart.as_view(),
        name='remove_from_cart'
    ),

    url(
        regex=r'^checkout/(?P<cart_id>\d+)$',
        view=views.CheckoutView.as_view(),
        name='checkout'
    ),

]

ecommerce/apps/cart/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.conf import settings

from ..catalogue.models import Product


class Cart(TimeStampedModel):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    status = models.CharField(
        max_length=255,
        choices=(
            ("open", 'open'),
            ("cancelled", 'cancelled'),
            ("submitted", "submitted"),
            ("processed", "processed"),
            ("delivered", "delivered")
        )
    )
    products = models.ManyToManyField(Product)

    class Meta:
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return str(self.pk) + " - " + str(self.owner)

    @property
    def total_price(self):
        total_sum = sum([i.price for i in self.products.all()])
        return total_sum

    @property
    def total_items(self):
        total = len(self.products.all())
        return total

ecommerce/apps/cart/views.py
from django.views.generic import View, DetailView
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render

from .models import Cart
from ..catalogue.models import Product


class AddToCart(View):

    def get(self, request, product_id, *args, **kwargs):
        cart_id = request.session.get('cart_id')
        if not cart_id:
            user = request.user
            if request.user.is_authenticated():
                cart = Cart(owner=user, status="open")
            else:
                cart = Cart(status="open")
            cart.save()
        else:
            cart = Cart.objects.get(id=int(cart_id))
        product = Product.objects.get(id=product_id)
        cart.products.add(product)
        # cart.save()
        request.session['cart_id'] = cart.id
        return HttpResponseRedirect(
            reverse('cart:cart_detail', args=(cart.id,))
        )


class RemoveFromCart(View):

    def get(self, request, product_id, *args, **kwargs):
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart = Cart.objects.get(id=int(cart_id))
            product = Product.objects.get(id=product_id)
            cart.products.remove(product)
        return HttpResponseRedirect(
            reverse('cart:cart_detail', args=(cart.id,))
        )

class CartDetailView(DetailView):
    model = Cart
    template_name = 'cart.html'


class CheckoutView(LoginRequiredMixin, View):
    # I haven't checked anything for Payment.
    # We can include Payment required later.
    template_name = "checkout_complete.html"

    def get(self, request, cart_id, *args, **kwargs):
        cart = get_object_or_404(Cart, id=int(cart_id))
        if cart.owner and cart.owner != request.user:
            pass
        if not cart.owner:
            cart.owner = request.user
        cart.status = "submitted"
        cart.save()
        del request.session['cart_id']
        return render(request, self.template_name)

ecommerce/apps/cart/templates/add_to_cart.html
{% extends 'base.html' %}

{% block content %}
  <h3> Your current Shopping Cart </h3>

  {% for product in cart.products.all %}
  <div>{{product.title}}</div>
  {% endfor %}
{% endblock content %}

ecommerce/apps/cart/templates/cart.html
{% extends 'base.html' %}

{% block content %}
  <div class="text-sm-center">
    <a href="{% url 'cart:checkout' object.id %}" class="btn btn-large btn-primary">Complete Checkout</a>
  </div>
  <h3> Your current Shopping Cart </h3>
  <table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th></th>
      <th>Item</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>  {% for product in object.products.all %}

    <tr>
      <td scope="row">{{forloop.counter}}</td>
      <td ><img style="max-height:100px" src="{{MEDIA_URL}}{{product.base_image}}"  alt=""></td>
      <td>{{product.title}}</td>
      <td>$ {{product.price}}</td>
      <td><a href = "{% url 'cart:remove_from_cart' product.id %}" class="btn btn-danger">Remove</a></td>
    </tr>
  {% endfor %}
  <tr >
    <td colspan="3" class="text-sm-right">Total:</td> <td> ${{object.total_price}}</td>
  </tr>
  </tbody>
  </table>

  <div class="text-sm-center">
    <a href="{% url 'cart:checkout' object.id %}" class="btn btn-large btn-primary">Complete Checkout</a>
  </div>


{% endblock content %}

ecommerce/apps/cart/templates/checkout_complete.html
{% extends 'base.html' %}

{% block content %}
  <h2>Thank you. Your order has been received </h2>

{% endblock content %}