config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('ecommerce.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^catalogue/', include('ecommerce.apps.catalogue.urls', namespace="catalogue")),
    url(r'^cart/', include('ecommerce.apps.cart.urls', namespace="cart")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

ecommerce/apps/cart/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView

    url(
        regex=r'^(?P<pk>\d+)$',
        view=views.CartDetailView.as_view(),
        name='cart_detail'
    ),

    url(
        regex=r'^add-to-cart/(?P<product_id>\d+)$',
        view=views.AddToCart.as_view(),
        name='add_to_cart'
    ),

    url(
        regex=r'^remove-from-cart/(?P<product_id>\d+)$',
        view=views.RemoveFromCart.as_view(),
        name='remove_from_cart'
    ),

    url(
        regex=r'^checkout/(?P<cart_id>\d+)$',
        view=views.CheckoutView.as_view(),
        name='checkout'
    ),

]

ecommerce/apps/catalogue/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^items/(?P<category_slug>[\w-]+)/$',
        view=views.ProductListView.as_view(),
        name='product_list_category'
    ),

    url(
        regex=r'^search/$',
        view=views.ProductSearchView.as_view(),
        name='search'
    ),

    url(
        regex=r'^(?P<product_slug>[\w-]+)/$',
        view=views.ProductDetailView.as_view(),
        name='product_detail'
    ),
]

ecommerce/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

ecommerce/apps/cart/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.conf import settings

from ..catalogue.models import Product


class Cart(TimeStampedModel):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    status = models.CharField(
        max_length=255,
        choices=(
            ("open", 'open'),
            ("cancelled", 'cancelled'),
            ("submitted", "submitted"),
            ("processed", "processed"),
            ("delivered", "delivered")
        )
    )
    products = models.ManyToManyField(Product)

    class Meta:
        verbose_name = "Cart"
        verbose_name_plural = "Carts"

    def __str__(self):
        return str(self.pk) + " - " + str(self.owner)

    @property
    def total_price(self):
        total_sum = sum([i.price for i in self.products.all()])
        return total_sum

    @property
    def total_items(self):
        total = len(self.products.all())
        return total

ecommerce/apps/catalogue/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class Category(TimeStampedModel):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Product(TimeStampedModel):

    title = models.CharField(max_length=255)
    categories = models.ManyToManyField(Category)
    price = models.FloatField()
    special_price = models.FloatField(null=True)
    base_image = models.ImageField(null=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.title


class AdditionalImages(TimeStampedModel):
    image = models.FileField()
    product = models.ForeignKey(Product, related_name='additional_images')

ecommerce/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    shipping_address = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

ecommerce/apps/cart/views.py
from django.views.generic import View, DetailView
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render

from .models import Cart
from ..catalogue.models import Product


class AddToCart(View):

    def get(self, request, product_id, *args, **kwargs):
        cart_id = request.session.get('cart_id')
        if not cart_id:
            user = request.user
            if request.user.is_authenticated():
                cart = Cart(owner=user, status="open")
            else:
                cart = Cart(status="open")
            cart.save()
        else:
            cart = Cart.objects.get(id=int(cart_id))
        product = Product.objects.get(id=product_id)
        cart.products.add(product)
        # cart.save()
        request.session['cart_id'] = cart.id
        return HttpResponseRedirect(
            reverse('cart:cart_detail', args=(cart.id,))
        )


class RemoveFromCart(View):

    def get(self, request, product_id, *args, **kwargs):
        cart_id = request.session.get('cart_id')
        if cart_id:
            cart = Cart.objects.get(id=int(cart_id))
            product = Product.objects.get(id=product_id)
            cart.products.remove(product)
        return HttpResponseRedirect(
            reverse('cart:cart_detail', args=(cart.id,))
        )

class CartDetailView(DetailView):
    model = Cart
    template_name = 'cart.html'


class CheckoutView(LoginRequiredMixin, View):
    # I haven't checked anything for Payment.
    # We can include Payment required later.
    template_name = "checkout_complete.html"

    def get(self, request, cart_id, *args, **kwargs):
        cart = get_object_or_404(Cart, id=int(cart_id))
        if cart.owner and cart.owner != request.user:
            pass
        if not cart.owner:
            cart.owner = request.user
        cart.status = "submitted"
        cart.save()
        del request.session['cart_id']
        return render(request, self.template_name)

ecommerce/apps/catalogue/views.py
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.db.models import Q

from .models import Product, Category


class ProductListView(ListView):
    model = Product
    template_name = "product_list.html"
    paginate_by = 21

    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs.get("category_slug"))
        return Product.objects.filter(categories=category)


class ProductSearchView(ListView):
    model = Product
    template_name = "product_list.html"
    paginate_by = 21

    def get_queryset(self):
        query = self.request.GET.get('q').lower()
        products = Product.objects.filter(
            Q(title__icontains=query) |
            Q(description__icontains=query)
        )
        return products


class ProductDetailView(DetailView):
    model = Product
    slug_url_kwarg = 'product_slug'
    template_name = "product_detail.html"

ecommerce/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

ecommerce/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Sample Ecommerce{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">Sample Ecommerce</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">


            <ul class="nav navbar-nav pull-xs-left" style="padding-left:40px">
              <form class="form-inline" method="GET" action="{% url 'catalogue:search' %}">
                <input class="form-control" name="q" type="text" placeholder="Search" value="{{request.GET.q}}">
                <button class="btn btn-success-outline" type="submit" >Search</button>
              </form>
            </ul>

            <ul class="nav navbar-nav pull-xs-left" style="padding-left:50px">

              <div class="btn-group">
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">Browse Categories</button>

                  <span class="sr-only">Toggle Dropdown</span>

                <div class="dropdown-menu" style="margin-right:-200px">

                    {% for category in categories %}
                      <div style="display: inline-block; padding: 0px 20px 0px 0px" >
                        <a  href="{% url 'catalogue:product_list_category' category.slug %}">{{category.title}}</a>
                      </div>
                    {% endfor %}

                </div>
              </div>
            </ul>



            <ul class="nav navbar-nav pull-xs-right">
              {% if current_cart %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'cart:cart_detail' current_cart.id %}">
                    Checkout

                      <span class="label label-pill label-default">{{current_cart.total_items}}</span>

                  </a>
                </li>
                {% endif %}
              {% if request.user.is_authenticated %}
                {% comment %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                {% endcomment %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                {% comment %}
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>
                {% endcomment %}
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container" style="margin-top: 10px">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

      <!-- Tether - a requirement for Bootstrap tooltips -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>